lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ear_logo_light.png
    - docs/images/nf-core-ear_logo_light.png
    - docs/images/nf-core-ear_logo_dark.png
    - lib/nfcore_external_java_deps.jar
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ear_logo_light.png
    - docs/images/nf-core-ear_logo_light.png
    - docs/images/nf-core-ear_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  prefix: sanger-tol
  skip:
    - igenomes
